from alpine:3


workdir /app

copy requirements.txt .

run apk update && \
apk add python3


copy requirements.txt .

run pip3 install -r requirements.txt

copy . . 


cmd FLASK_APP=app flask run --port 5000 --host 0.0.0.0
